language: python
python:
  - '2.7'

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install tox-travis

# command to run tests
script: tox

deploy:
  provider: pypi
  user: vmware_column
  password:
    secure: MAHFyKpuUb5M9nYcqhc65SmCxC1GgFDKmYcNyoqeOqQBl3XG4/uvYxQkQ2h0RRZfMJiyNGE2fKKQSeXoavMrijDGitiiZ8IXkydP8hbNsanCL/kj0E/3MGXgIi08mOUUiKVuIn3zcDsqHUQgdRbwnMvHRVNrmeTifWwp9CrXQB0364I9CnW74O/yRJ6zewwrRKBN/xm1kWX4vyAmHvae59XcA70ViSnfqEYRKGrAZn10r7875HFRpfDHIbG8KawDKsZW0yAWkoRutSRoJ0HyyeTMptdJoEhx7Egze/sI7vy+a9i1SQ1M2FNQX1BXCPaNhO+som7QYzfY0FySGWzDVrkjCU4CDPM/1YSC42XLiG0QFilmy++OnhpAX+jMyWfxkjzw2ezou+5Y7X878Ga9pjYUA+8ceQemyhauWu0UlmYgli/cqldJ+Ac21Gtq2P/Pfor4RDE4GzTo1/rMgDow5Ly+UvE0dDlmeYed/n6jQH6uXWDSyJSVNVYcEKQw33A8kBX7KyjamU1rDtcvZGgGoajiXcb7KSjrX5IhxUNChadiriaQx4zRMNv5/4kFxXYTocR0xPguBe+Mo/50Fl72/Q4oVTXrdFsYBTX7R9QZebAYfSZRTMXvcn83M4M3IBknBpnIl4BF689lLnK30egzFTUOo6HTbNbVZrSAqdCSPys=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_upload_docs: true
