# Copyright (c) 2017 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

language: python
python:
  - "2.7_with_system_site_packages"

dist:
  - xenial

# command to install dependencies
install:
  - pip install tox-travis
  - pip install -r test-requirements.txt

# command to run tests
script: tox

after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION

before_deploy:
  - sudo apt-get install python-setuptools python-all debhelper fakeroot
  - sudo pip install stdeb
  - export PYTHONPATH=/usr/local/lib/python2.7/dist-packages; python setup.py --command-packages=stdeb.command bdist_deb

deploy:
  - provider: pypi
    user: vmware_column
    password:
      secure: MAHFyKpuUb5M9nYcqhc65SmCxC1GgFDKmYcNyoqeOqQBl3XG4/uvYxQkQ2h0RRZfMJiyNGE2fKKQSeXoavMrijDGitiiZ8IXkydP8hbNsanCL/kj0E/3MGXgIi08mOUUiKVuIn3zcDsqHUQgdRbwnMvHRVNrmeTifWwp9CrXQB0364I9CnW74O/yRJ6zewwrRKBN/xm1kWX4vyAmHvae59XcA70ViSnfqEYRKGrAZn10r7875HFRpfDHIbG8KawDKsZW0yAWkoRutSRoJ0HyyeTMptdJoEhx7Egze/sI7vy+a9i1SQ1M2FNQX1BXCPaNhO+som7QYzfY0FySGWzDVrkjCU4CDPM/1YSC42XLiG0QFilmy++OnhpAX+jMyWfxkjzw2ezou+5Y7X878Ga9pjYUA+8ceQemyhauWu0UlmYgli/cqldJ+Ac21Gtq2P/Pfor4RDE4GzTo1/rMgDow5Ly+UvE0dDlmeYed/n6jQH6uXWDSyJSVNVYcEKQw33A8kBX7KyjamU1rDtcvZGgGoajiXcb7KSjrX5IhxUNChadiriaQx4zRMNv5/4kFxXYTocR0xPguBe+Mo/50Fl72/Q4oVTXrdFsYBTX7R9QZebAYfSZRTMXvcn83M4M3IBknBpnIl4BF689lLnK30egzFTUOo6HTbNbVZrSAqdCSPys=
    distributions: sdist bdist_wheel
    skip_upload_docs: true
    skip_cleanup: true

  - provider: releases
    api_key:
      secure: VlK+KBBAJLFGYgNWS1vq+xsE1rgb0/TN/QC84I8RyBBwOS+36rvJ3VdHuarmEAJBEc+t4MMIsn68L3NULaBK/3DOF0IQqFoZzyhDV8vZn0g06NWUoDlWx0bvUJ4z72QqoF+O4vGA1nEBfFThiXjf0Qz6o2oMW+O8awCH5TEae9gmMdjPKL9mWS8VBQileUbPigjKKrelX0XGW6mGS5Tmy+ONoxr4UTjv1hWvou8UlYGtNgvZd6fRXY8bv19FEfkMIcrlTdWayHaonz1+He1B5daqIDBHkgziIkugFc0TEc7Kw6qeR0It4ECI/hb4SnS6NmfYio3YKSNRl/yE4Ez1WC1tjMjLkJQ7p25pfcBTiWZJ6PENnFmV3VxmbsJi8y60MwFqG8LfE+T0g4gpfhpKy4YOiDKNBqG6s16bOpZX4Y8YMAnDk6Gl0+sCqvgvwmIjqgf4WMxz28c7yD5QMs8GVA9m2gmQe6KxZ4mBRYqkPftsMmiNqL0v9vzDIp+HYgOjqBhdCiEIWLfeIXM5dbZGFmkYgn+ms96aBXtib7uxbCpMIDZ4XBhcFQPbm1hKy9U8mt3zUGf60tYCIeLXQL6Hf4GSF84s77N2HKzHHVXHqP7OnTHApSWiqnjRPrbBFGc5WrmYx8shy+YHY1D67sn9xJuIOzPSTdyUwQNlOhqHKcA=
    file_glob: true
    file:
      - dist/column*.whl
      - deb_dist/python-column*.deb
    skip_cleanup: true
    on:
      repo: vmware/column
